quarkus.openapi.generator.server.use=openapitools
quarkus.openapi.generator.server.spec=backoffice-openapi.yaml
quarkus.openapi.generator.server.base-package=org.smartbar.backoffice

quarkus.datasource.username=greg
quarkus.datasource.password=greg
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/smartbarbo
quarkus.hibernate-orm.database.generation=drop-and-create
