quarkus.openapi.generator.server.use=openapitools
quarkus.openapi.generator.server.spec=openapi.yaml
quarkus.openapi.generator.server.base-package=org.smartbar.backoffice

%dev.quarkus.datasource.username=greg
%dev.quarkus.datasource.password=greg
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/smartbarbo
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
